---
- name: Local cowrie installation
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Ensure variables are set
      ansible.builtin.include_vars:
        dir: ./defaults
        extensions:
          - "yml"

    - name: Configure and install cowrie
      ansible.builtin.include_tasks: tasks/main.yml
...
