---
collections:
  - name: ansible.posix
    version: '2.1.0'
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.crypto
    version: '3.0.3'
    source: https://github.com/ansible-collections/community.crypto.git
    type: git
  - name: community.docker
    version: '4.6.2'
    source: https://github.com/ansible-collections/community.docker.git
    type: git
  - name: community.general
    version: '11.1.1'
    source: https://github.com/ansible-collections/community.general.git
    type: git

roles:
  - name: konstruktoid.baseline
    version: 'v0.2.0'
    src: https://github.com/konstruktoid/ansible-role-baseline.git
    scm: git
  - name: konstruktoid.docker_rootless
    version: 'v0.61.0'
    src: https://github.com/konstruktoid/ansible-role-docker-rootless.git
    scm: git
