---
collections:
  - name: ansible.posix
    version: '1.5.4'
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.crypto
    version: '2.21.1'
    source: https://github.com/ansible-collections/community.crypto.git
    type: git
  - name: community.docker
    version: '3.11.0'
    source: https://github.com/ansible-collections/community.docker.git
    type: git
  - name: community.general
    version: '9.2.0'
    source: https://github.com/ansible-collections/community.general.git
    type: git

roles:
  - name: konstruktoid.baseline
    version: 'v0.2.0'
    src: https://github.com/konstruktoid/ansible-role-baseline.git
    scm: git
  - name: konstruktoid.docker_rootless
    version: 'v0.52.0'
    src: https://github.com/konstruktoid/ansible-role-docker-rootless.git
    scm: git
