---
- name: Cowrie rootless container block
  when: not rootful_enabled
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ docker_user_info.uid }}"
    PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
    DOCKER_HOST: "unix:///run/user/{{ docker_user_info.uid }}/docker.sock"
  block:
    - name: Add cowrie rootless container systemd service
      become: true
      become_user: "{{ docker_user }}"
      ansible.builtin.template:
        src: files/cowrie_container.service.j2
        dest: "{{ docker_user_info.home }}/.config/systemd/user/cowrie_container.service"
        backup: 'yes'
        mode: 0600

    - name: Enable and start the cowrie container
      become: true
      become_user: "{{ docker_user }}"
      ansible.builtin.systemd:
        name: cowrie_container
        enabled: 'yes'
        state: started
        scope: user
        daemon_reload: 'yes'

- name: Cowrie rootful container block
  when: rootful_enabled
  block:
    - name: Add cowrie rootful container systemd service
      become: true
      ansible.builtin.template:
        src: files/cowrie_container.service.j2
        dest: /etc/systemd/system/cowrie_container.service
        backup: 'yes'
        mode: 0600

    - name: Enable and start the cowrie container
      become: true
      ansible.builtin.systemd:
        name: cowrie_container
        enabled: 'yes'
        state: started
        daemon_reload: 'yes'
...
