---
- name: cowrie container block
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ docker_user_info.uid }}"
    PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
    DOCKER_HOST: "unix:///run/user/{{ docker_user_info.uid }}/docker.sock"
  block:
    - name: add cowrie container systemd service
      become: 'yes'
      become_user: "{{ docker_user }}"
      ansible.builtin.template:
        src: files/cowrie_container.service.j2
        dest: "{{ docker_user_info.home }}/.config/systemd/user/cowrie_container.service"
        backup: 'yes'
        mode: 0600

    - name: enable and cowrie container
      become: 'yes'
      become_user: "{{ docker_user }}"
      ansible.builtin.systemd:
        name: cowrie_container
        enabled: 'yes'
        state: started
        scope: user
        daemon_reload: 'yes'
...
