---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      rootless:
        docker_user: cowrie
        rootful_enabled: false
      rootful:
        docker_user: cowrie
        rootful_enabled: true
platforms:
  - name: rootless
    box: bento/ubuntu-24.04
    config_options:
      vm.boot_timeout: 600
      ssh.key_type: ed25519
    instance_raw_config_args:
      - vbguest.auto_update = false
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--uart1', '0x3F8', '4']
      - customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]
    memory: 1024
  - name: rootful
    box: bento/ubuntu-24.04
    config_options:
      vm.boot_timeout: 600
      ssh.key_type: ed25519
    instance_raw_config_args:
      - vbguest.auto_update = false
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--uart1', '0x3F8', '4']
      - customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
