---
- name: Verify
  hosts: all
  any_errors_fatal: true

  tasks:
    - name: Reboot host
      become: true
      ansible.builtin.reboot:

    - name: Wait for the host and reconnect
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}'
        delay: 10
        timeout: 120

    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_hostname }}"

    - name: Install sshpass
      become: true
      ansible.builtin.package:
        name: sshpass
        state: present

    - name: Register docker_user info
      become: true
      ansible.builtin.user:
        name: "{{ docker_user }}"
      check_mode: 'yes'
      register: docker_user_info

    - name: Rootless verification block
      when: not rootful_enabled
      block:
        - name: Verify docker_user creation
          ansible.builtin.command: id "{{ docker_user }}"
          register: id_docker_user
          changed_when: id_docker_user.rc != 0
          failed_when: id_docker_user.rc != 0

        - name: Verify docker_user subuid
          ansible.builtin.command: grep "^{{ docker_user }}:" /etc/subuid
          register: subuid_docker_user
          changed_when: subuid_docker_user.rc != 0
          failed_when: subuid_docker_user.rc != 0

        - name: Verify docker_user subgid
          ansible.builtin.command: grep "^{{ docker_user }}:" /etc/subgid
          register: subgid_docker_user
          changed_when: subgid_docker_user.rc != 0
          failed_when: subgid_docker_user.rc != 0

        - name: Verify docker_user dockerd
          ansible.builtin.shell: >
            set -o pipefail &&
            ps -fe | grep -E 'dockerd$|dockerd -s fuse-overlayfs$' | awk '{print $1}'
          args:
            executable: /bin/bash
          register: ps_dockerd
          changed_when: docker_user[:7] not in ps_dockerd.stdout
          failed_when: docker_user[:7] not in ps_dockerd.stdout

        - name: Verify running cowrie container
          become: true
          become_user: "{{ docker_user }}"
          community.docker.docker_container_info:
            name: cowrie
          register: cowrie_container_running
          changed_when: not cowrie_container_running
          failed_when: not cowrie_container_running

        - name: Try to connect to container
          ansible.builtin.command:
            cmd: |
              sshpass -p {{ ansible_nodename | shuffle(seed='k10d') | join('') }}
              ssh -p2222 -o StrictHostKeyChecking=no -o ConnectTimeout=5 127.0.0.1 'grep "^phil.*Phil California" /etc/passwd'
          register: ssh_connect
          changed_when: false
          failed_when: "'Phil California' not in ssh_connect.stdout"

    - name: Rootful verification block
      when: rootful_enabled
      block:
        - name: Verify docker_user creation
          ansible.builtin.command: id "{{ docker_user }}"
          register: id_docker_user
          changed_when: id_docker_user.rc != 0
          failed_when: id_docker_user.rc != 0

        - name: Verify docker_user subuid
          ansible.builtin.command: grep "^{{ docker_user }}:" /etc/subuid
          register: subuid_docker_user
          changed_when: subuid_docker_user.rc != 0
          failed_when: subuid_docker_user.rc != 0

        - name: Verify docker_user subgid
          ansible.builtin.command: grep "^{{ docker_user }}:" /etc/subgid
          register: subgid_docker_user
          changed_when: subgid_docker_user.rc != 0
          failed_when: subgid_docker_user.rc != 0

        - name: Verify docker_user dockerd
          ansible.builtin.shell: >
            set -o pipefail &&
            ps -fe | grep -E '^root.*dockerd|^root.*containerd$'
          args:
            executable: /bin/bash
          register: ps_dockerd
          changed_when: ps_dockerd.rc != 0
          failed_when: ps_dockerd.rc != 0

        - name: Verify running cowrie container
          become: true
          community.docker.docker_container_info:
            name: cowrie
          register: cowrie_container_running
          changed_when: not cowrie_container_running
          failed_when: not cowrie_container_running

        - name: Try to connect to container
          ansible.builtin.command:
            cmd: |
              sshpass -p {{ ansible_nodename | shuffle(seed='k10d') | join('') }}
              ssh -p2222 -o StrictHostKeyChecking=no -o ConnectTimeout=5 127.0.0.1 'grep "^phil.*Phil California" /etc/passwd'
          register: ssh_connect
          changed_when: false
          failed_when: "'Phil California' not in ssh_connect.stdout"

    - name: Verify logging
      ansible.builtin.shell: >
        set -o pipefail &&
        grep 'cowrie.command.input.*CMD: grep.*^phil.*Phil California.../etc/passwd' "{{ docker_user_info.home }}/cowrie/var/log/cowrie.json"
      args:
        executable: /bin/bash
      register: grep_logs
      changed_when: grep_logs.rc != 0
      failed_when: grep_logs.rc != 0
...
