on: [push, pull_request]
name: YAML lint
jobs:
  konstruktoidYAMLLint:
    name: Konstruktoid YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Konstruktoid YAML lint
        uses: ./action-lint
