on:
  schedule:
    - cron: "0 0 * * *"
name: "Close stale issues"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity, without any activity it will be closed in 5 days.'
          days-before-stale: 30
          days-before-close: 5
